sudo: false
language: bash
env:
  - BASH=5.0.3
addons:
  apt:
    sources:
      - sourceline: 'ppa:duggan/bats'
    packages:
      - bats
      - bc
before_script:
  - docker pull bash:$BASH
script: ./test.sh